version: 2
jobs:
  build:
    branches:
      only:
        - vNext
    docker:
      - image: circleci/node:7.10
        environment:
          COVERALLS_SERVICE_NAME: circleci
          COVERALLS_SERVICE_JOB_ID: $CIRCLE_BUILD_NUM
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
#      - run:
#          name: "JavaScript Linter"
#          command: yarn lint -- --format junit -o reports/junit/js-lint-results.xml
      - run:
          name: "JavaScript Test Suite"
          environment:
            JEST_JUNIT_OUTPUT: reports/junit/js-test-results.xml
          command: npm run test:ci
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit