version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # - persist_to_workspace:
      #     root: ~/repo
      #     paths: .
  # test-merge:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/repo
  #     - run:
  #         name: "JavaScript Test Suite"
  #         environment:
  #           JEST_JUNIT_OUTPUT: reports/junit/js-test-results.xml
  #           COVERALLS_SERVICE_NAME: circleci
  #           COVERALLS_SERVICE_JOB_ID: $CIRCLE_BUILD_NUM
  #         command: npm run test:ci
  #     # Store our test results + Output
  #     - store_test_results:
  #         path: reports/junit
  #     - store_artifacts:
  #         path: reports/junit
  #     # Allows deploy to pickup where this job leaves off
  #     - persist_to_workspace:
  #         root: ~/repo
  #         paths: .
  # test-pr:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/repo
      - run:
          name: "JavaScript Test Suite"
          environment:
            JEST_JUNIT_OUTPUT: reports/junit/js-test-results.xml
            COVERALLS_SERVICE_NAME: circleci
            COVERALLS_SERVICE_JOB_ID: $CIRCLE_BUILD_NUM
          command: npm run test:unit -- --coverage --coverageReporters=text-lcov
      # Store our test results + Output
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      # Allows deploy to pickup where this job leaves off
      # - persist_to_workspace:
      #     root: ~/repo
      #     paths: .
  # deploy:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/repo
  #     # - run: echo -e "$NPM_USER\n$NPM_PASS\n$NPM_EMAIL" | npm login
      - run: 
          name: Write NPM Token to ~/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      # - run:
      #     name: Bump version number
      #     command: npm version 3.0.1-alpha
      - run:
          name: Publish package
          command: npm publish --tag next

      # - run: 
      #     name: Install dot-json package
      #     command: npm install dot-json

      # - run:
      #     name: Write version to package.json
      #     command: $(yarn bin)/dot-json package.json version ${CIRCLE_TAG:1}

workflows:
  version: 2
  # Pull Requests
  build-test:
    jobs:
      - setup:
          filters:
            branches:
              only: vNext
      - test-pr:
          requires:
            - setup
  # Merges to vNext
  build-test-deploy:
    jobs:
      - setup:
          filters:
            branches:
              ignore: vNext
      # - test-pr:
      #     requires:
      #       - setup
      # - deploy:
      #     requires:
      #       - test-pr