version: 2
jobs:
  build:
    docker:
        - image: circleci/node:7.10
          environment:
            COVERALLS_SERVICE_NAME: circleci
            COVERALLS_SERVICE_JOB_ID: $CIRCLE_BUILD_NUM
      working_directory: ~/repo
      steps:
        - checkout
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
        - run: npm install
        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}
        - persist_to_workspace:
          root: ~/repo
          paths: .
  test-merge:
    steps:
      - attach_workspace:
        at: ~/repo
      - run:
          name: "JavaScript Test Suite"
          environment:
            JEST_JUNIT_OUTPUT: reports/junit/js-test-results.xml
          command: npm run test:unit -- --coverage --coverageReporters=text-lcov | coveralls
      # Store our test results + Output
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      # Allows deploy to pickup where this job leaves off
      - persist_to_workspace:
        root: ~/repo
        paths: .
  test-pr:
    steps:
      - attach_workspace:
        at: ~/repo
      - run:
          name: "JavaScript Test Suite"
          environment:
            JEST_JUNIT_OUTPUT: reports/junit/js-test-results.xml
          command: npm run test:unit -- --coverage --coverageReporters=text-lcov
      # Store our test results + Output
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      # Allows deploy to pickup where this job leaves off
      - persist_to_workspace:
        root: ~/repo
        paths: .
  deploy:
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
  version: 2
  my_workflow:
    jobs:
      - build
      # Merge
      - test-merge:
        filters:
          branches:
            only: vNext
        requires:
          - build
      # Pull Requests
      - test-pr:
        filters:
          branches:
            ignore: vNext
        requires:
          - build